# Generated by Django 4.0.6 on 2022-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfconv', '0003_remove_userpdf_time_userpdf_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdf',
            name='filename',
        ),
        migrations.AddField(
            model_name='userpdf',
            name='PdfFileMerger',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
