# Generated by Django 4.0.6 on 2022-07-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfconv', '0004_remove_userpdf_filename_userpdf_pdffilemerger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpdf',
            old_name='PdfFileMerger',
            new_name='pdffile',
        ),
    ]
